#!/bin/bash
# Quick start guide - run this in terminal

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  AndroidVisionAutomator - Autonomous Android MCP          ║"
echo "║  AI-driven Android agent (No ADB, No Root)                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if API key is set
if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo "⚠️  ANTHROPIC_API_KEY not set"
    echo ""
    echo "Get your API key from: https://console.anthropic.com"
    echo "Then run:"
    echo "  export ANTHROPIC_API_KEY=sk-..."
    echo ""
fi

echo "📚 DOCUMENTATION"
echo "  Quick Start        → README.md"
echo "  Architecture       → docs/ARCHITECTURE.md"
echo "  Development Guide  → DEVELOPMENT.md"
echo "  Project Summary    → PROJECT_SUMMARY.md"
echo ""

echo "🚀 QUICK START (5 minutes)"
echo ""
echo "1. Setup environment:"
echo "   chmod +x setup.sh"
echo "   ./setup.sh"
echo ""
echo "2. Set API key:"
echo "   export ANTHROPIC_API_KEY=sk-..."
echo ""
echo "3. Build Android app:"
echo "   cd android-app"
echo "   ./gradlew build"
echo "   ./gradlew installDebug"
echo ""
echo "4. Enable service on phone:"
echo "   Settings → Accessibility → AndroidVisionAutomator → Enable"
echo ""
echo "5. Test it:"
echo "   Say: \"Send a message to Mom\""
echo ""

echo "📁 PROJECT STRUCTURE"
echo ""
echo "Core Components:"
echo "  ✓ android-app/                  Android app source"
echo "    ├── accessibility/            AutomationAccessibilityService"
echo "    ├── models/                   Data structures"
echo "    ├── agent/                    Task executor"
echo "    └── safety/                   Permission manager"
echo ""
echo "  ✓ backend/                      Python cloud services"
echo "    ├── services/                 Claude LLM client"
echo "    ├── app.py                    REST API server"
echo "    └── models/                   API models"
echo ""
echo "  ✓ mcp-server/                   MCP server"
echo "    └── android_vision_mcp.py    Orchestrator"
echo ""
echo "Configuration:"
echo "  ✓ config.json                   Safety policies & settings"
echo "  ✓ requirements.txt              Python dependencies"
echo "  ✓ setup.sh                      Setup script"
echo ""

echo "🧠 ARCHITECTURE (7 Layers)"
echo ""
echo "  1️⃣  Input Layer        Voice/text command capture"
echo "  2️⃣  Intent Parser      Claude LLM extracts intent"
echo "  3️⃣  Task Planner       Claude LLM creates action plan"
echo "  4️⃣  Action Executor    Accessibility Service performs UI actions"
echo "  5️⃣  Screen Feedback    UI tree analysis & capture"
echo "  6️⃣  Verification       Detects success/failure, replans on error"
echo "  7️⃣  Safety Guardian    Enforces whitelist & permissions"
echo ""

echo "💡 EXAMPLE USAGE"
echo ""
echo "Commands your device understands:"
echo "  • \"Send a message to Mom\""
echo "  • \"Open WhatsApp and message Dad\""
echo "  • \"Open YouTube and search for cats\""
echo "  • \"Turn on WiFi\""
echo "  • \"Open Google Maps\""
echo ""

echo "🔐 SAFETY FEATURES"
echo "  ✓ App whitelist (only approved apps)"
echo "  ✓ Dangerous action blocking"
echo "  ✓ Sensitive action confirmation"
echo "  ✓ Rate limiting & timeouts"
echo "  ✓ Audit logging"
echo "  ✓ Kill switch always available"
echo ""

echo "📞 HELP"
echo ""
echo "  Detailed docs:  see docs/ARCHITECTURE.md"
echo "  Developer tips: see DEVELOPMENT.md"
echo "  Code examples:  see examples.py"
echo "  All settings:   see config.json"
echo ""

echo "✅ Everything is ready! 🚀"
echo ""
echo "Next: Read README.md or run ./setup.sh"
echo ""
